workflows:
  ios-workflow:
    name: iOS Build (signed IPA)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

      # Ceci suppose que tu ajoutes les credentials dans Codemagic UI:
      # - App Store Connect API key (ou Apple ID)
      # - iOS Development certificate (.p12)
      # - Provisioning profile (Development)

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install

      - name: Build signed IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
