workflows:
  ios-workflow:
    name: iOS Build (unsigned IPA - xcarchive method)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Flutter deps
        script: |
          flutter clean
          flutter pub get

      - name: CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS (no codesign)
        script: |
          flutter build ios --release --no-codesign

      - name: Xcode archive (iphoneos, no codesign)
        script: |
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/Runner.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Package unsigned IPA from archive
        script: |
          APP_PATH="build/Runner.xcarchive/Products/Applications/Runner.app"

          echo "=== App path ==="
          ls -la "$APP_PATH"

          echo "=== Frameworks check ==="
          ls -la "$APP_PATH/Frameworks" || true
          du -sh "$APP_PATH" || true
          du -sh "$APP_PATH/Frameworks" || true

          rm -rf build/Payload
          mkdir -p build/Payload
          cp -R "$APP_PATH" build/Payload/

          cd build
          rm -f iot-ble-scanner.ipa
          zip -r iot-ble-scanner.ipa Payload

          echo "=== IPA content (top) ==="
          unzip -l iot-ble-scanner.ipa | head -n 80

    artifacts:
      - build/iot-ble-scanner.ipa
      - build/Runner.xcarchive
