workflows:
  ios-workflow:
    name: iOS Build (unsigned IPA for Sideloadly + min iOS check)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Flutter deps
        script: |
          set -e
          flutter clean
          flutter pub get

      - name: CocoaPods
        script: |
          set -e
          cd ios
          pod install
          cd ..

      - name: Build iOS (no codesign)
        script: |
          set -e
          flutter build ios --release --no-codesign

      - name: Xcode archive (iphoneos, no codesign, force deployment target)
        script: |
          set -e
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/Runner.xcarchive \
            archive \
            IPHONEOS_DEPLOYMENT_TARGET=12.0 \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Package unsigned IPA (ditto + preserve symlinks + plist dump)
        script: |
          set -e

          APP_PATH="build/Runner.xcarchive/Products/Applications/Runner.app"

          echo "=== APP_PATH listing ==="
          ls -la "$APP_PATH" || true

          echo "=== Frameworks listing ==="
          ls -la "$APP_PATH/Frameworks" || true

          echo "=== Sizes ==="
          du -sh "$APP_PATH" || true
          du -sh "$APP_PATH/Frameworks" || true

          echo "=== Runner architecture ==="
          file "$APP_PATH/Runner" || true

          echo "=== Info.plist key dump (MinimumOSVersion, SDK) ==="
          plutil -p "$APP_PATH/Info.plist" | grep -E "MinimumOSVersion|DTPlatformVersion|DTSDKName|DTXcode" || true

          # Build IPA structure
          rm -rf build/Payload
          mkdir -p build/Payload

          # Copy bundle safely
          ditto "$APP_PATH" build/Payload/Runner.app

          # Zip into an IPA (IMPORTANT: -y preserves symlinks)
          cd build
          rm -f iot-ble-scanner.ipa
          zip -r -y iot-ble-scanner.ipa Payload

          echo "=== IPA size ==="
          ls -lh iot-ble-scanner.ipa

          echo "=== IPA content (top) ==="
          unzip -l iot-ble-scanner.ipa | head -n 80

    artifacts:
      - build/iot-ble-scanner.ipa
      - build/Runner.xcarchive
