workflows:
  ios-workflow:
    name: iOS Build (unsigned IPA – symlink safe)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Flutter deps
        script: |
          flutter clean
          flutter pub get

      - name: CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS (no codesign)
        script: |
          flutter build ios --release --no-codesign

      - name: Xcode archive (iphoneos, no codesign)
        script: |
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/Runner.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Package unsigned IPA (preserve symlinks)
        script: |
          APP_PATH="build/Runner.xcarchive/Products/Applications/Runner.app"

          echo "=== Frameworks size ==="
          du -sh "$APP_PATH/Frameworks"

          rm -rf build/Payload
          mkdir -p build/Payload
          cp -R "$APP_PATH" build/Payload/

          cd build
          rm -f iot-ble-scanner.ipa

          # 🔑 CRITICAL: -y to preserve symlinks
          zip -r -y iot-ble-scanner.ipa Payload

          echo "=== IPA size ==="
          ls -lh iot-ble-scanner.ipa

    artifacts:
      - build/iot-ble-scanner.ipa
