workflows:
  ios-workflow:
    name: iOS Build (unsigned IPA for Sideloadly)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Flutter packages
        script: |
          flutter clean
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS (device, no codesign)
        script: |
          flutter build ios --release --no-codesign

      - name: Package unsigned IPA
        script: |
          cd build/ios/iphoneos

          # Create Payload structure required by IPA
          rm -rf Payload
          mkdir -p Payload
          cp -R Runner.app Payload/

          # Zip as .ipa
          rm -f iot-ble-scanner.ipa
          zip -r iot-ble-scanner.ipa Payload

          # Sanity checks (very useful in logs)
          echo "=== IPA content (top) ==="
          unzip -l iot-ble-scanner.ipa | head -n 60

          echo "=== Runner arch ==="
          file Payload/Runner.app/Runner || true

          echo "=== Sizes ==="
          ls -lh iot-ble-scanner.ipa
          du -sh Payload/Runner.app

    artifacts:
      - build/ios/iphoneos/iot-ble-scanner.ipa
